version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    # ports:
    #   - '5432:5432'
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: "tom"
    volumes:
      - ../..:/ws:cached
    command: sleep infinity
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '4000:4000'
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
